# Generated by Django 3.0.7 on 2020-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
